package main

import (
	"fmt"
	"github.com/xulehexuwei/scikits"
)

// yaml 直接生成结构体的在线工具 https://www.printlove.cn/tools/yaml2go

type AutoGenerated struct {
	Mysql Mysql `yaml:"mysql"`
	Mongo Mongo `yaml:"mongo"`
	Redis Redis `yaml:"redis"`
	Minio Minio `yaml:"minio"`
}

type Mysql struct {
	Db       string `yaml:"db"`
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	User     string `yaml:"user"`
	Password string `yaml:"password"`
}

type Mongo struct {
	User     string `yaml:"user"`
	Password string `yaml:"password"`
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Db       string `yaml:"db"`
}

type Redis struct {
	Host string `yaml:"host"`
	Port string `yaml:"port"`
	Pass string `yaml:"pass"`
}

type Minio struct {
	Endpoint        string `yaml:"endpoint"`
	DomainProxy     string `yaml:"domainProxy"`
	AccessKeyID     string `yaml:"accessKeyID"`
	SecretAccessKey string `yaml:"secretAccessKey"`
	UseSSL          bool   `yaml:"useSSL"`
	BucketName      string `yaml:"bucketName"`
}

var (
	YamlStruct AutoGenerated
)

// yaml文件和结构体绑定
func main() {
	scikits.MyViper.Unmarshal(&YamlStruct)

	fmt.Println(YamlStruct)

	fmt.Println(scikits.MyViper.GetString("logs.filepath"))
}
